const productNameMap = {
    "pineapple": "Ananas (İthal)",
    "pear": "Armut",
    "avocado": "Avakado",
    "quince": "Ayva",
    "okra": "Bamya",
    "cranberry bean": "Barbunya",
    "peas": "Bezelye",
    "red pepper": "Biber (Capya) Tarla",
    "charleston pepper": "Biber (Çarli)",
    "stuffed pepper": "Biber (Dolmalık)",
    "broccoli": "Brokoli",
    "strawberry": "Çilek",
    "dill": "Dereotu",
    "tomato": "Domates",
    "apple": "Elma (Golden)",
    "artichoke": "Enginar",
    "plum": "Erik",
    "green beans": "Fasulye (Çalı)",
    "basil": "Fesleğen",
    "lettuce": "Marul",
    "grapefruit": "Greyfurt",
    "carrot": "Havuç",
    "coconut": "Hindistan Cevizi (İthal)",
    "spinach": "Ispanak",
    "pumpkin": "Kabak (Bal)",
    "cauliflower": "Karnabahar",
    "watermelon": "Karpuz (1. Kalite)",
    "melon": "Kavun",
    "apricot": "Kayısı",
    "celery": "Kereviz",
    "curly lettuce": "Kıvırcık",
    "cherry": "Kiraz",
    "kiwi": "Kivi (İthal)",
    "asparagus": "Kuşkonmaz (İthal)",
    "red cabbage": "Lahana (Kırmızı)",
    "lemon": "Limon",
    "mango": "Mango (İthal)",
    "mushroom": "Mantar",
    "parsley": "Maydanoz",
    "corn": "Mısır",
    "banana": "Muz (Yerli)",
    "mint": "Nane",
    "pomegranate": "Nar",
    "nectarine": "Nektarin",
    "beetroot": "Pancar",
    "papaya": "Papaya (İthal)",
    "potato": "Patates",
    "onion": "Soğan (Kuru)",
    "peach": "Şeftali",
    "watercress": "Tere",
    "radish": "Turp",
    "grape": "Üzüm"
  };
  